apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: podinfo
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  backend:
    serviceName: podinfo
    servicePort: 80
